name: Bench
on:
  workflow_dispatch:
    inputs:
      repeation:
        description: benchmark repeation times
        required: true
        default: 3
        type: number
jobs:
  benchmark:
    name: Run benchmark
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Run benchmark
        run: node benchmark.mjs -n=${{ inputs.repeation }}
